"use client";

import { mdiChevronDown, mdiDotsVertical, mdiExportVariant } from "@mdi/js";
import { Card } from "@/components/ui/Card";
import { Icon } from "@/components/ui/Icon";
import { TwitterFeed } from "@/components/common/TwitterFeed";
import { useI18n } from "@/lib/i18n";

export function AboutSection() {
  const { t } = useI18n();
  return <Card id="about" className="space-y-6 border-[color:var(--color-border)] p-6">
    <header><h2 className="text-3xl font-semibold tracking-tight text-[color:var(--color-foreground)]">{t("component.mainNav.about")}</h2></header>
    <div className="grid gap-6"><Card className="overflow-hidden p-0"><TwitterFeed showHeader={false} /></Card></div>
    <Card className="p-6">
      <h3 className="text-lg font-semibold text-[color:var(--color-foreground)]">{t("about.credits.title")}</h3>
      <div className="about-credits mt-4 space-y-4 text-sm leading-6 text-[color:var(--color-muted-foreground)]">
        <p>{t("about.credits.contents[0]")} <a className="font-medium text-[color:var(--color-primary)] underline underline-offset-4 transition-opacity hover:opacity-90" href="https://hololive.jetri.co/">HoloTools</a> {t("about.credits.contents[1]")} <a className="font-medium text-[color:var(--color-primary)] underline underline-offset-4 transition-opacity hover:opacity-90" href="https://github.com/holofans/holoapi">holoapi</a>.<br />{t("about.credits.contents[2]")}</p>
        <p>{t("about.credits.contents[3]")} <a className="font-medium text-[color:var(--color-primary)] underline underline-offset-4 transition-opacity hover:opacity-90" href="https://en.hololive.tv/terms" target="_blank" rel="noopener noreferrer">{t("about.credits.contents[4]")}</a></p>
        <p>By using this site you are agreeing to be bound by the <a className="font-medium text-[color:var(--color-primary)] underline underline-offset-4 transition-opacity hover:opacity-90" href="https://www.youtube.com/t/terms">Youtube Terms of Service</a>.</p>
      </div>
    </Card>
    <div className="grid gap-6"><Card className="p-6"><h3 className="text-lg font-semibold text-[color:var(--color-foreground)]">{t("about.faq.title")}</h3><div className="mt-4 faq-list">
      <Faq title={t("about.faq.ytchatHeader")}><>{t("about.faq.ytchatContent")}<br /><a className="text-sky-300 hover:text-sky-200" href="https://support.mozilla.org/en-US/kb/third-party-cookies-firefox-tracking-protection?redirectslug=disable-third-party-cookies">{t("about.faq.ytchatFirefox")}</a></></Faq>
      <Faq title={t("about.faq.autoplayHeader")}><div className="space-y-4"><p>{t("about.faq.autoplayContent")}</p><div className="space-y-4"><div><div className="mb-2 text-sm font-normal text-[color:var(--color-foreground)]">Safari</div><img width="80%" src="https://www.imore.com/sites/imore.com/files/styles/large/public/field/image/2017/07/safari-custom-settings-websites-mac-screenshot-06.jpg?itok=ONVYTcno" alt="" /></div><div><div className="mb-2 text-sm font-normal text-[color:var(--color-foreground)]">Firefox</div><img width="80%" src="https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/firefox/files/2019/04/Screen-Shot-2019-04-01-at-11.21.21-AM.png" alt="" /></div></div></div></Faq>
      <Faq title={t("about.faq.mobile.title")}><><p>{t("about.faq.mobile.content.summary")}</p><ul className="mt-3 space-y-2 pl-5"><li>{t("about.faq.mobile.content.android.0")} <Icon icon={mdiDotsVertical} size="sm" className="mx-1 text-sky-300" /> {t("about.faq.mobile.content.android.1")}</li><li>{t("about.faq.mobile.content.ios.0")} <Icon icon={mdiExportVariant} size="sm" className="mx-1 text-sky-300" /> {t("about.faq.mobile.content.ios[1]")}</li></ul></></Faq>
      <Faq title={t("about.faq.favorite.disappear.title")}>{t("about.faq.favorite.contents.0")}</Faq>
      <Faq title={t("about.faq.subber.title")}><>{t("about.faq.subber.contents.0")} <a className="text-sky-300 hover:text-sky-200" href="https://forms.gle/xkN4w8fyPr6YTGfx6">{t("about.faq.subber.contents.1")}</a> {t("about.faq.subber.contents.2")}</></Faq>
      <Faq title={t("about.faq.videoLinkage")}>{t("about.faq.videoLinkageContent")}</Faq>
      <Faq title={t("about.faq.quitHolodex")}>{t("about.faq.quitHolodexContent")}</Faq>
      <Faq title={t("about.faq.feedback.title")}>{t("about.faq.feedback.contents.0")}</Faq>
      <Faq title={t("about.faq.support.title")}><div dangerouslySetInnerHTML={{ __html: t("about.faq.support.contents.0") }} /></Faq>
      <Faq title={t("about.privacyPolicy")}><PrivacyPolicy /></Faq>
      <Faq title={t("about.gdpr")}><>{t("about.gdprContent")} <span className="font-normal text-[color:var(--color-foreground)]">{t("about.gdprDeletion")}</span></></Faq>
    </div></Card></div>
  </Card>;
}

function Faq({ title, children }: { title: React.ReactNode; children: React.ReactNode }) {
  return <details className="faq-item"><summary className="faq-trigger"><span>{title}</span><Icon icon={mdiChevronDown} size="sm" className="faq-chevron" /></summary><div className="faq-content">{children}</div></details>;
}

function PrivacyPolicy() {
  return <div className="space-y-4">
    <p>This Privacy Policy governs the manner in which Holodex collects, uses, maintains, and discloses information collected from users (each, a &quot;User&quot;) of the Holodex website (&quot;Site&quot;). This privacy policy applies to the Site and all products and services offered by Holodex.</p>
    <div><h4 className="text-base font-normal text-[color:var(--color-foreground)]">Holodex First Party Information collection and usage:</h4><p className="mt-2">We collect limited personal identification information from Users in a variety of ways, including, but not limited to, when Users visit our Site, register on the Site, fill out a form, and in connection with other activities, services, features or resources we make available on our Site.</p><p className="mt-2">We will collect personal identification information from Users only if they voluntarily submit such information to us. Users can always refuse to supply personal identification information and use the Site without logging in.</p><p className="mt-2">i) Information Access: When you log in using your social media account, we will only access the basic information required to facilitate your login. This typically includes your email address or social media handle. We will not retrieve or store any other personal data from your social media account. We will also store the minimum amount of ID or email handle used to distinctly link a Holodex account with a Social Media Account so we may facilitate future logins.</p><p className="mt-2">ii) Limited Use: The information obtained from your social media account is solely for the purpose of allowing you to log into our service. We will not use this information for identification purposes outside of this function or share it with third parties without your explicit consent.</p><p className="mt-2">iii) No Posting: We will not post any content to your social media accounts on your behalf or access your contacts, friends, or followers.</p><p className="mt-2">iv) Revoking Access: You can revoke our access to your social media account at any time through your social media platform&apos;s settings. Revoking our access will not affect your account with us, but you may need to set up an alternative login method for our service.</p><p className="mt-2">Changes to This Clause: Any changes to our social media login policy will be updated on this page. We recommend that you periodically review this clause for any changes.</p></div>
    <div><h4 className="text-base font-normal text-white">Third Party Information collection and usage:</h4><h5 className="mt-3 text-sm font-normal uppercase tracking-[0.18em] text-[color:var(--color-foreground)]">1. Google Analytics</h5><p className="mt-2">We use Google Analytics, a service provided by Google, Inc., to analyze our website traffic. Google Analytics utilizes cookies to track visitor interactions and collects information about how visitors use our site. This data might include your IP address, browser type, browser version, the pages of our site that you visit, the time and date of your visit, the time spent on those pages, and other statistics.</p><p className="mt-2">The data collected is primarily used to report on website usage to help us understand our visitors&apos; preferences and to enhance the user experience. Please refer to Google&apos;s privacy policy.</p><h5 className="mt-3 text-sm font-normal uppercase tracking-[0.18em] text-[color:var(--color-foreground)]">2. YouTube & Twitch Embeds</h5><p className="mt-2">Our website may feature embedded videos from YouTube (owned by Google, Inc.) or Twitch (owned by Twitch Interactive, Inc.). When you watch these videos, these platforms may set cookies on your device and collect data such as your IP address, your browser type, and the page you visited on our site.</p><p className="mt-2">We&apos;ve added links below to their respective privacy policies.</p><h5 className="mt-3 text-sm font-normal uppercase tracking-[0.18em] text-[color:var(--color-foreground)]">Your Choices</h5><p className="mt-2">You can control and limit the data that third-party services collect by using the respective settings in your browser or device and by consulting the privacy settings specific to each third-party service.</p><h5 className="mt-3 text-sm font-normal uppercase tracking-[0.18em] text-[color:var(--color-foreground)]">Contact Us about Privacy</h5><p className="mt-2">If you have concerns about the data these third parties collect or wish to find out more about your data protection rights, we encourage you to visit their respective privacy policies.</p><p className="mt-2">Your privacy is of paramount importance to us, and we are committed to ensuring the best standards are upheld. If you have any questions or concerns regarding our use of social media logins, please contact our team on discord.</p><div className="space-y-2"><a className="block text-sky-300 hover:text-sky-200" href="https://policies.google.com/privacy">Google and Youtube Privacy Policy</a><a className="block text-sky-300 hover:text-sky-200" href="https://www.twitch.tv/p/en/legal/privacy-notice/">Twitch Privacy Policy</a></div></div>
  </div>;
}
